# Introduction

This is a book created from markdown and executable code.

See @knuth84 for additional discussion of literate programming.

```{r}
# 安装 BiocManager（如果尚未安装）
if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")

# 使用 BiocManager 安装 Bioconductor 包（phyloseq, Maaslin2）
BiocManager::install(c("phyloseq", "Maaslin2"))

# 安装 CRAN 包
install.packages(c("tidyverse", "ggpubr", "vegan"))
```

```{r}
library(phyloseq)
library(tidyverse)
library(ggpubr)
library(vegan)
library(Maaslin2)


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Fig. 1e:  Beta Diversity
# Calculate the distance matrix:
beta_dist <- vegdist(t(otu), index = 'bray')
# Scaling results with NMDS
mds <- metaMDS(beta_dist)
# Extract PCoA axes and format
mds_data <- as.data.frame(mds$points)
mds_data$`Sample` <- rownames(mds_data)
mds_data <- mds_data %>% left_join(sample_data(ps.rar) %>% as.matrix() %>% 
                                    as.data.frame %>% select(Diet, Day) %>% rownames_to_column('Sample')) %>% 
  mutate(beta_type = 'Bray-Curtis')

# Plot results
mds_data$Group = paste(mds_data$Diet, mds_data$Day)
mds_data$Group = factor(mds_data$Group, 
                        levels = c('CON Day 0','LM Day 0','CON Day 28','LM Day 28'))
p = ggplot(mds_data, aes(x = MDS1, y = MDS2, color = Group)) +
    geom_point(size = 2) + 
    stat_ellipse(size = 1) +
    theme_classic(base_size = 20) + 
    xlab('PCoA 1') + ylab('PCoA 2') +
    ggtitle('Bray-Curtis Beta Diversity')
data_1e = p$data

ggsave('Plots/Bacteriome/Fig. 1e - Beta Diversity.png',height = 5, width = 7)
```

```{r Calculate Beta statistics}
# CENTROID DISTANCES (PERMANOVA)~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Format datasets
count_mat = otu %>% t() %>% as.data.frame() %>% rownames_to_column('Sample') %>% 
  left_join(mds_data %>% select(Sample, Diet, Day, Group))
      
# CON D0 vs D28
temp_group = count_mat$Group[str_detect(count_mat$Sample, 'CON')]
cm_con = otu %>% t %>% .[str_detect(rownames(.),'CON'),]
beta_dist_con <- vegdist(cm_con, index = 'bray')
pathotype.adonis.con <- ((adonis(beta_dist_con ~ temp_group))$aov.tab)[1,6] # p value
      
# LM D0 vs D28
temp_group = count_mat$Group[str_detect(count_mat$Sample, 'LM')]
cm_lm = otu %>% t %>% .[str_detect(rownames(.),'LM'),]
beta_dist_lm <- vegdist(cm_lm, index = 'bray')
pathotype.adonis.lm <- ((adonis(beta_dist_lm ~ temp_group))$aov.tab)[1,6] # p value
      
# D0 CON vs LM
temp_group = count_mat$Group[str_detect(count_mat$Sample, 'D0')]
cm_d0 = otu %>% t %>% .[str_detect(rownames(.),'D0'),]
beta_dist_d0 <- vegdist(cm_d0, index = 'bray')
pathotype.adonis.d0 <- ((adonis(beta_dist_d0 ~ temp_group))$aov.tab)[1,6] # p value

# D28 CON vs LM
temp_group = count_mat$Group[str_detect(count_mat$Sample, 'D28')]
cm_d28 = otu %>% t %>% .[str_detect(rownames(.),'D28'),]
beta_dist_d28 <- vegdist(cm_d28, index = 'bray')
pathotype.adonis.d28 <- ((adonis(beta_dist_d28 ~ temp_group))$aov.tab)[1,6] # p value

# CONCATENATE STATISTICS ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

beta_stats = tibble(Stat = rep('Centroid Distances',4),
                    Comparison = c('CON D0 vs D28','LM D0 vs D28',
                                   'D0 CON vs LM','D28 CON vs LM'),
                    pval = c(pathotype.adonis.con, pathotype.adonis.lm,
                             pathotype.adonis.d0, pathotype.adonis.d28)) %>% 
  mutate(`p adj` = p.adjust(pval)) %>% 
  mutate(`Beta Measure` = 'Bray-Curtis') %>% 
  select(`Beta Measure`, Stat, everything()) %>% 
  mutate(pval = round(pval,4),`p adj` = round(`p adj`,4))

write.csv(beta_stats,'Results Files/Bacteriome/Beta Diversity Statistics.csv',row.names = F)

# Clean up environment
rm(beta_dist,beta_dist_con,beta_dist_d0,beta_dist_d28,beta_dist_lm,
   cm_con,cm_lm,cm_d0,cm_d28,
   pathotype.adonis.con,pathotype.adonis.d0,pathotype.adonis.d28,
   pathotype.adonis.lm,
   count_mat, mds, mds_data, temp_group)
```


```{r}
# 1. 切换到目标文件夹 (注意这里的斜杠方向)
setwd("C:/Users/lenovo/Desktop/lunwenfuxian/fig1e")

# 2. 加载需要的包
library(tidyverse)
library(ggpubr)
# 如果你的文件真的是 .xlsx 结尾，必须加载 readxl 包来读取
library(readxl) 

# 3. 读取表格数据 (已修正读取 Excel 的函数)
# 如果你的文件其实是 CSV 格式，请改回 mds_data <- read_csv("你的文件名.csv")
mds_data <- read_excel("Source Data Fig 1.xlsx")

# 4. 设置分组因子
mds_data$Group = factor(mds_data$Group, 
                        levels = c('CON Day 0','LM Day 0','CON Day 28','LM Day 28'))

# 5. 画图
p = ggplot(mds_data, aes(x = MDS1, y = MDS2, color = Group)) +
    geom_point(size = 2) + 
    stat_ellipse(linewidth = 1) +  
    theme_classic(base_size = 20) + 
    xlab('NMDS 1') + ylab('NMDS 2') + 
    ggtitle('Bray-Curtis Beta Diversity')

print(p)

# 6. 保存图片
# 因为前面已经切换了工作目录，所以这里会自动保存在 fig1e 文件夹下
# 如果你的 fig1e 下面没有 'Plots/Bacteriome/' 这两个子文件夹，直接写文件名即可：
ggsave('Fig_1e_Beta_Diversity.png', plot = p, height = 5, width = 7)
```